package com.sqlitekotline

data class ProductAttributes(
    var id: Int = 0,
    var name: String = "",
    var descripations: String = "",
    var frantImage: String = "",
    var backImage: String ="",
    var ramTitle: String = "",
    var ramDetails: String = "",
    var ramEg: String = "",
    var displayTitle:String="",
    var displayDiscription:String="",
    var proccesor: String = "",
    var mainCameraTitle: String = "",
    var mainCameraDiscription: String = "",
    var frontCameraTitle: String = "",
    var frontCameraDiscription: String = "",
    var gamingGpuTitle: String = "",
    var gamingGpuDiscription: String = "",
    var networkSpeedTitle: String = "",
    var networkSpeedDiscription: String = "",
    var bodyStroageTitle: String = "",
    var bodyStroageDiscription: String = "",
    var operatingSystemTitle: String = "",
    var operatingSystemDiscription: String = "",
    var networkFrequencyTitle: String = "",
    var networkFrequencyDiscription: String = "",
    var companyAccessoryTitle: String = "",
    var companyAccessoryDiscription: String = "",
    var conclusionTitle: String = "",
    var conclusionDiscription: String = "",
    var water_proff: String = "",
    var ssd_space: String = "",
    var price: String = "",
    var check:Boolean =false
    )